spring:
  application:
    name: nacos
  cloud:
    # 注册及配置中心
    nacos:
      # 注册中心
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 9527

management:
  endpoints:
    web:
      exposure:
        include: '*'
